// strings.js — English (default, WAbot-style) + Roman Urdu.
// Use: import { tr } from './lib/strings.js'; tr(lang, 'nav.forms')

export const LANGS = ['en', 'ur'];

const en = {
  appName: 'Leave Form App',
  appTag: 'Make leave forms, sign them, print them.',

  nav: { forms: 'New Forms', keys: 'API Keys', signs: 'Signatures', settings: 'Settings' },
  back: 'Back',
  continue: 'Continue',
  close: 'Close',
  cancel: 'Cancel',
  save: 'Save',
  remove: 'Remove',
  add: 'Add',
  test: 'Test',
  retry: 'Retry',

  steps: { upload: 'Upload', review: 'Review', setup: 'Setup', generate: 'Generate' },

  auth: {
    signIn: 'Sign In',
    welcome: 'Welcome back',
    signInSub: 'Sign in to sync your signatures and holidays.',
    create: 'Create Account',
    createSub: 'One account keeps your keys and signatures synced.',
    email: 'Email',
    password: 'Password',
    emailPh: 'you@email.com',
    passPhLogin: 'Your password',
    passPhSignup: 'Minimum 6 characters',
    signInBtn: 'Sign In',
    signUpBtn: 'Create Account',
    toSignup: 'New here? Create an account',
    toLogin: 'Already have an account? Sign in',
    checkEmail: 'Check your email',
    checkEmailSub:
      'We sent a confirmation link to your email. Click it, then sign in here.',
    resend: 'Resend email',
    resent: 'Confirmation email sent again.',
    needBoth: 'Please enter both email and password.',
    errors: {
      INVALID_CREDENTIALS: 'Wrong email or password.',
      ALREADY_REGISTERED: 'This email is already registered. Please sign in.',
      WEAK_PASSWORD: 'Password must be at least 6 characters.',
      INVALID_EMAIL: 'That email address looks invalid.',
      NOT_CONFIRMED: 'Please confirm your email first — click the link we sent you.',
      UNCONFIRMED: 'Please confirm your email first — click the link we sent you.',
      UNKNOWN: 'Something went wrong. Please try again.',
    },
  },

  upload: {
    title: 'Upload Excel File',
    sub: 'Drop the sick-leave register here. .xlsx, .xls and .csv all work.',
    drop: 'Choose a file or drop it here',
    dropPhone: 'Works from your phone too.',
    month: 'Which month is this register for?',
    monthNote: 'If the Date column has only day numbers (like 18, 19, 20), they are read as this month.',
    leaveType: 'Which leave is this?',
    leaveTypeSick: 'Sick leave',
    leaveTypeCasual: 'Casual leave',
    leaveTypeAnnual: 'Annual leave',
    needCols: 'The file should have these columns:',
    colsNote:
      'Ecode, Name, Father, Designation, Department, Date, Reason. If names differ slightly the app tries to detect them, and you can fix the mapping in the next step.',
    reading: 'Reading file...',
    readFail: 'Could not read the file. Check it and upload again.',
  },

  review: {
    title: 'Review & Map Columns',
    sub: 'Match each field to the right column. Name and Date are required.',
    smartTitle: 'Fix Urdu with Gemini',
    smartSub:
      'Clean up names, designations, departments and reasons into proper Urdu script using your API keys.',
    keysConfigured: (n) => `${n} key${n === 1 ? '' : 's'} configured`,
    manageKeys: 'Manage keys',
    smartOn: 'Smart Urdu fix is ON',
    runFix: 'Fix Urdu with Gemini',
    running: 'Gemini is working...',
    mapTitle: 'Column Mapping',
    mapSub: 'Match each field to the right column. Name and Date are required.',
    rowsTitle: (n) => `Rows (${n})`,
    rowsSub: 'You can fix Urdu text here. Give it a look before printing.',
    noRows: 'No rows found.',
    removeRow: 'Remove this row',
    needMapping:
      'To continue, Name and Date columns must be mapped and at least one row is needed.',
  },

  keys: {
    title: 'Gemini API Keys',
    sub: 'Keys are saved to your account and sync across your devices. Work is split across all keys in parallel.',
    testAll: 'Test all keys',
    addPh: 'Paste a new Gemini API key',
    addBtn: 'Add key',
    bulkTitle: 'Add several keys at once (bulk import)',
    bulkPh: 'Paste keys, one per line or separated by commas',
    importBtn: 'Import all',
    working: 'This key works.',
    keyCount: (n) => `${n} key${n === 1 ? '' : 's'} saved`,
    secureNote: 'Keys stay in your account vault. Never share them.',
  },

  signs: {
    title: 'Signatures',
    sub: 'Signatures printed on the leave forms.',
    empty: 'No signatures yet. Add one above.',
  },

  signs: {
    title: 'Signatures',
    sub: 'Signatures printed on the leave forms.',
    explainer:
      'For each signature, set two things: Position (which line on the form it goes on) and Rule (when it applies). An empty rule means the signature goes on every form. Below each signature you can see exactly when it will be used.',
    posEmployee: 'Employee',
    posDeptHead: 'Department Head',
    posHr: 'HR Manager',
    posCustom: 'Custom',
    fldDepartment: 'Department',
    fldDesignation: 'Designation',
    fldReason: 'Reason',
    opContains: 'contains',
    opEquals: 'equals',
    uploadHint: 'Upload PNG / JPG',
    labelPh: 'Label, e.g. Dept Head Sign',
    valuePh: 'e.g. STITCHING',
    save: 'Save signature',
    saving: 'Saving...',
    replace: 'Replace (upload a new signature)',
    defaultBadge: 'Default',
    defaultHrNote: 'This is the HR signature, used on every form.',
    removeDefault: 'Remove default signature',
    restoreDefault: 'Restore default HR signature',
    defaultRemovedNote: 'Default HR signature is off. No signature will print on the HR line unless you upload one.',
    confirmDelete: 'Delete this signature?',
    ruleAll: (pos) => pos + ' line on every form.',
    ruleWhen: (pos, field, needle, op) => pos + ' line, only when ' + field + ' ' + op + ' "' + needle + '".',
    opContainsText: 'contains',
    opEqualsText: 'is equal to',
    sessionOnly:
      'Signatures are saved for this session only. Sign in to sync them with your account.',
    loadFail: 'Could not load from the server. Running in local mode for this session.',
    loginPrompt: 'Sign in so your signatures sync with your account.',
    saveFail: 'Could not save. Please try again.',
    deleteFail: 'Could not delete. Please try again.',
    replaceFail: 'Could not replace. Please try again.',
    empty: 'No signatures yet. Add one above.',
    loading: 'Loading...',
    saved: 'Saved',
    saveDb: 'Save',
    saveTitle: 'Save to database',
    sessionSavedTitle: 'Already saved in this session',
    delete: 'Delete',
  },

  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    security: 'Security',
    pinLock: 'App PIN lock',
    holidays: 'Public Holidays',
    language: 'Language',
    pinAbout: 'With a PIN set, the app asks for it on every fresh open.',
    pinNew: 'New PIN (4 to 8 digits)',
    pinConfirm: 'Repeat PIN',
    pinSetBtn: 'Set PIN',
    pinOld: 'Old PIN',
    pinChangeNew: 'New PIN (to change)',
    pinChangeBtn: 'Change',
    pinRemoveBtn: 'Remove PIN',
    pinNeed4: 'PIN must be 4+ digits and both entries must match.',
    pinSaved: 'PIN set. It will be asked next time the app opens.',
    pinSaveFail: 'Could not save PIN.',
    pinNeedBoth: 'Old and new PIN must both be 4+ digits.',
    pinWrong: 'Old PIN is wrong.',
    pinChanged: 'PIN changed.',
    pinNeedOld: 'Enter the old PIN to remove it.',
    pinRemoved: 'PIN removed.',
    pinOn: 'PIN is on. Enter the old PIN to change or remove it.',
    holMonth: 'Month',
    holFetch: 'Get Karachi holidays with Gemini',
    holFetching: 'Loading...',
    holManual: 'Add manually',
    holNoKey: 'Without an API key this is manual mode. Sundays are off automatically; add other holidays here.',
    holNone: 'No holidays saved for this month.',
    holReview: 'Review, then confirm',
    holAddDate: 'Add date',
    holConfirm: 'Confirm save',
    holSaving: 'Saving...',
    holSavedAs: (m, src) => `Confirmed holidays for ${m}${src ? ` (via ${src === 'gemini' ? 'Gemini' : 'manual'})` : ''}`,
    holNoResult: 'No holidays found. Add them manually.',
    holFail: 'Could not load holidays. Add them manually.',
    holSaveFail: 'Could not save to database, but the list is set for this session.',
  },

  generate: {
    title: 'Leave Forms Ready',
    preview: 'Print preview',
    ready: (n) => `${n} form${n === 1 ? '' : 's'} ready.`,
    signed: (n) => `${n} form${n === 1 ? '' : 's'} will be signed.`,
    skipped: (n) =>
      `${n} row${n === 1 ? '' : 's'} ha${n === 1 ? 's' : 've'} a date problem and won't print. Fix the date in the Review step.`,
    print: 'Print / Save PDF',
    download: 'Download printable file',
    newBatch: 'Start new batch',
    empty: 'No printable forms.',
    printNote:
      'Print opens the A4 landscape layout. Choose Save as PDF there to make a PDF. The downloaded file can be opened and printed later.',
  },

  user: { signOut: 'Sign out', signedInAs: 'Signed in as' },

  busy: {
    working: 'Working...',
    parsing: 'File read. Preparing Urdu...',
    fixing: (d, total) => `Fixing Urdu with Gemini... ${d}/${total}`,
    parseFail: 'Could not prepare rows. Please try again.',
    mapping: 'Updating column mapping...',
    geminiFail: (fixed, attempted) =>
      `Could not reach Gemini. ${fixed}/${attempted} values fixed, the rest use local Urdu. Reason:`,
    geminiOk: (n) => `Gemini fixed ${n} names/departments/reasons in Urdu.`,
    rerun: 'Fixing names and departments in Urdu with Gemini...',
    rerunFail: 'Smart fix did not run. Local Urdu values are safe.',
  },
};

const ur = {
  appName: 'Leave Form App',
  appTag: 'Chhutti ke form banayein, sign karein, print karein.',

  nav: { forms: 'Naye Forms', keys: 'API Keys', signs: 'Dastakhat', settings: 'Settings' },
  back: 'Pechay',
  continue: 'Aagay',
  close: 'Band karein',
  cancel: 'Cancel',
  save: 'Save',
  remove: 'Hatayein',
  add: 'Add karein',
  test: 'Test',
  retry: 'Dobara',

  steps: { upload: 'Upload', review: 'Review', setup: 'Setup', generate: 'Generate' },

  auth: {
    signIn: 'Login',
    welcome: 'Khush aamdeed',
    signInSub: 'Login karein taake signatures aur chhuttiyan sync hon.',
    create: 'Naya Account',
    createSub: 'Ek account se keys aur signatures har device par sync honge.',
    email: 'Email',
    password: 'Password',
    emailPh: 'aap@email.com',
    passPhLogin: 'Aap ka password',
    passPhSignup: 'Kam az kam 6 harf',
    signInBtn: 'Login karein',
    signUpBtn: 'Account banayein',
    toSignup: 'Naye hain? Account banayein',
    toLogin: 'Pehle se account hai? Login karein',
    checkEmail: 'Email check karein',
    checkEmailSub:
      'Hum ne aap ke email par confirmation link bheja hai. Us par click karein, phir yahan login karein.',
    resend: 'Email dobara bhejein',
    resent: 'Confirmation email dobara bhej di gayi.',
    needBoth: 'Email aur password dono likhein.',
    errors: {
      INVALID_CREDENTIALS: 'Email ya password ghalat hai.',
      ALREADY_REGISTERED: 'Ye email pehle se registered hai. Login karein.',
      WEAK_PASSWORD: 'Password kam az kam 6 harf ka ho.',
      INVALID_EMAIL: 'Email address durust nahi hai.',
      NOT_CONFIRMED: 'Pehle email confirm karein — jo link bheja hai us par click karein.',
      UNCONFIRMED: 'Pehle email confirm karein — jo link bheja hai us par click karein.',
      UNKNOWN: 'Kuch ghalat ho gaya. Dobara koshish karein.',
    },
  },

  upload: {
    title: 'Excel File Upload karein',
    sub: 'Sick leave register wali file yahan dein. .xlsx, .xls ya .csv sab chalenge.',
    drop: 'File chunein ya yahan drop karein',
    dropPhone: 'Phone se bhi file select ho jayegi.',
    month: 'Ye register kis month ka hai?',
    monthNote: 'Date column me sirf din likha ho (jaise 18, 19, 20) to usi month ka samjha jayega.',
    leaveType: 'Ye kaunsi leave hai?',
    leaveTypeSick: 'Sick leave',
    leaveTypeCasual: 'Casual leave',
    leaveTypeAnnual: 'Annual leave',
    needCols: 'File mein ye columns hone chahiye:',
    colsNote:
      'Ecode, Name, Father, Designation, Department, Date, Reason. Naam thore mukhtalif bhi hon to app khud pehchanne ki koshish karegi, aur agle step mein aap mapping khud theek kar sakte hain.',
    reading: 'File parhi ja rahi hai...',
    readFail: 'File parhne mein masla hua. File dobara check karke upload karein.',
  },

  review: {
    title: 'Columns Check karein',
    sub: 'Har field ke liye sahi column chunein. Name aur Date lazmi hain.',
    smartTitle: 'Gemini se Urdu theek karwain',
    smartSub: 'Naam aur department ke naam Gemini se saaf Urdu me likhwayein.',
    keysConfigured: (n) => `${n} key mehfooz ${n === 1 ? 'hai' : 'hain'}`,
    manageKeys: 'Keys sambhalein',
    smartOn: 'Smart Urdu fix ON hai',
    runFix: 'Gemini se Urdu theek karwain',
    running: 'Gemini kaam kar raha hai...',
    mapTitle: 'Column Mapping',
    mapSub: 'Har field ke liye sahi column chunein. Name aur Date lazmi hain.',
    rowsTitle: (n) => `Rows (${n})`,
    rowsSub: 'Urdu text yahan theek kar sakte hain. Print se pehle aik nazar dekh lein.',
    noRows: 'Koi row nahi mili.',
    removeRow: 'Ye row hata dein',
    needMapping:
      'Aagay ke liye Name aur Date column ka map hona aur kam az kam aik row hona zaroori hai.',
  },

  keys: {
    title: 'Gemini API Keys',
    sub: 'Keys aap ke account me save hoti hain aur har device par sync hoti hain. Kaam sab keys me barabar bant ta hai.',
    testAll: 'Sab keys test karein',
    addPh: 'Nayi Gemini API key yahan paste karein',
    addBtn: 'Key add karein',
    bulkTitle: 'Ek sath kai keys paste karni hain? (bulk import)',
    bulkPh: 'Keys paste karein, har line par ek ya comma se alag kar ke',
    importBtn: 'Sab import karein',
    working: 'Ye key theek kaam kar rahi hai.',
    keyCount: (n) => `${n} key mehfooz ${n === 1 ? 'hai' : 'hain'}`,
    secureNote: 'Keys aap ke account vault me rehti hain. Kisi se share na karein.',
  },

  signs: {
    title: 'Dastakhat',
    sub: 'Chhutti ke formon par chhapne wale dastakhat.',
    empty: 'Abhi koi dastakhat nahi hai. Upar se naya add karein.',
  },

  signs: {
    title: 'Dastakhat',
    sub: 'Leave form par lagne wale dastakhat.',
    explainer:
      'Har dastakhat ke liye 2 cheezein batayein: Position (form par kis line par lagega) aur Rule (kab lagega). Rule khaali ho to wo har form par lagega. Neeche har dastakhat ke saath likha hai ke wo kab use hoga.',
    posEmployee: 'Mulazim',
    posDeptHead: 'Department Head',
    posHr: 'HR Manager',
    posCustom: 'Custom',
    fldDepartment: 'Department',
    fldDesignation: 'Designation',
    fldReason: 'Reason',
    opContains: 'mein ho',
    opEquals: 'barabar ho',
    uploadHint: 'PNG / JPG upload karein',
    labelPh: 'Naam, masalan Dept Head Sign',
    valuePh: 'masalan STITCHING',
    save: 'Dastakhat save karein',
    saving: 'Save ho raha hai...',
    replace: 'Replace karein (naya dastakhat upload karein)',
    defaultBadge: 'Default',
    defaultHrNote: 'Ye HR ka dastakhat hai, har form par lagega.',
    removeDefault: 'Default dastakhat hata dein',
    restoreDefault: 'Default HR dastakhat wapas lagayein',
    defaultRemovedNote: 'Default HR dastakhat off hai. HR line par koi dastakhat nahi lagega jab tak aap khud upload na karein.',
    confirmDelete: 'Is dastakhat ko delete karein?',
    ruleAll: (pos) => pos + ' ki line par, har form par.',
    ruleWhen: (pos, field, needle, op) => pos + ' ki line par, sirf jab ' + field + ' "' + needle + '" ' + op + '.',
    opContainsText: 'mein ho',
    opEqualsText: 'ke barabar ho',
    sessionOnly:
      'Dastakhat sirf is session ke liye save honge. Account se sync ke liye login karein.',
    loadFail: 'Server se load nahi ho saka. Is session ke liye local mode me chal raha hai.',
    loginPrompt: 'Login karein taake dastakhat aap ke account se sync hon.',
    saveFail: 'Save nahi ho saka. Dobara try karein.',
    deleteFail: 'Delete nahi ho saka. Dobara try karein.',
    replaceFail: 'Replace nahi ho saka. Dobara try karein.',
    empty: 'Abhi koi dastakhat nahi hai. Upar se naya add karein.',
    loading: 'Load ho raha hai...',
    saved: 'Saved',
    saveDb: 'Save',
    saveTitle: 'Database me save karein',
    sessionSavedTitle: 'Is session me already saved hai',
    delete: 'Delete',
  },

  settings: {
    title: 'Settings',
    appearance: 'Naqsh',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    security: 'Security',
    pinLock: 'App PIN lock',
    holidays: 'Chhuttiyan',
    language: 'Zubaan',
    pinAbout: 'PIN lagane ke baad app kholne par PIN manga jayega.',
    pinNew: 'Naya PIN (4 se 8 hindse)',
    pinConfirm: 'PIN dobara likhein',
    pinSetBtn: 'PIN set karein',
    pinOld: 'Purana PIN',
    pinChangeNew: 'Naya PIN (tabdeeli ke liye)',
    pinChangeBtn: 'Tabdeel karein',
    pinRemoveBtn: 'PIN khatam karein',
    pinNeed4: 'PIN kam az kam 4 hindse hon aur dono ek jaise hon.',
    pinSaved: 'PIN laga diya gaya. Agli dafa app kholne par manga jayega.',
    pinSaveFail: 'PIN save nahi ho saka.',
    pinNeedBoth: 'Purana aur naya dono PIN kam az kam 4 hindse hon.',
    pinWrong: 'Purana PIN ghalat hai.',
    pinChanged: 'PIN tabdeel kar diya gaya.',
    pinNeedOld: 'Khatam karne ke liye purana PIN dein.',
    pinRemoved: 'PIN khatam kar diya gaya.',
    pinOn: 'PIN laga hua hai. Tabdeel ya khatam karne ke liye purana PIN dein.',
    holMonth: 'Mahina',
    holFetch: 'Gemini se Karachi holidays lao',
    holFetching: 'La rahe hain...',
    holManual: 'Manual add',
    holNoKey: 'API key ke baghair manual mode hai. Sundays automatically off hote hain, baqi holidays yahan add kar lein.',
    holNone: 'Is month ke liye koi holiday save nahi hai.',
    holReview: 'Review karein, phir confirm karein',
    holAddDate: 'Date add karein',
    holConfirm: 'Confirm save',
    holSaving: 'Saving...',
    holSavedAs: (m, src) => `${m} ki confirmed holidays${src ? ` (${src === 'gemini' ? 'Gemini se' : 'Manual'})` : ''}`,
    holNoResult: 'Gemini se koi holiday nahi mili. Manual add kar lein.',
    holFail: 'Gemini se holidays nahi mil sake. Manual add kar lein.',
    holSaveFail: 'Database me save nahi ho saka, lekin list is session me set hai.',
  },

  generate: {
    title: 'Leave Forms Tayyar hain',
    preview: 'Print preview',
    ready: (n) => `${n} form tayyar ${n === 1 ? 'hai' : 'hain'}.`,
    signed: (n) => `${n} form par dastakhat lagen ge.`,
    skipped: (n) =>
      `${n} row mein tareekh ka masla hai, is liye woh print nahi hongi. Review step mein ja kar tareekh theek karein.`,
    print: 'Print / PDF save karein',
    download: 'HTML download karein',
    newBatch: 'Naya batch shuru karein',
    empty: 'Koi printable form nahi hai.',
    printNote:
      'Print dabane par A4 landscape layout khulega. Wahan Save as PDF chun kar PDF bhi bana sakte hain. Download wali file ko baad mein bhi khol kar print kiya ja sakta hai.',
  },

  user: { signOut: 'Logout', signedInAs: 'Login hai:' },

  busy: {
    working: 'Kaam ho raha hai...',
    parsing: 'File parh li. Urdu tayyar ki ja rahi hai...',
    fixing: (d, total) => `Gemini se Urdu theek ho rahi hai... ${d}/${total}`,
    parseFail: 'Rows tayyar karne mein masla hua. Dobara koshish karein.',
    mapping: 'Column mapping update ho rahi hai...',
    geminiFail: (fixed, attempted) =>
      `Gemini se rabta nahi ho saka. ${fixed}/${attempted} values theek huin, baqi par local Urdu lagi hai. Wajah:`,
    geminiOk: (n) => `Gemini ne ${n} naam/department/reason Urdu me theek kar diye.`,
    rerun: 'Gemini se naam aur department Urdu me theek kiye ja rahe hain...',
    rerunFail: 'Smart fix nahi chal saka. Local Urdu wali values mehfooz hain.',
  },
};

export const STRINGS = { en, ur };

/** tr('en', 'nav.forms') — supports function values called with args. */
export function tr(lang, path, ...args) {
  const table = STRINGS[lang] || STRINGS.en;
  const parts = String(path).split('.');
  let v = table;
  for (const p of parts) v = v && v[p];
  if (typeof v === 'function') return v(...args);
  if (typeof v === 'string') return v;
  const fb = STRINGS.en;
  v = fb;
  for (const p of parts) v = v && v[p];
  if (typeof v === 'function') return v(...args);
  return typeof v === 'string' ? v : path;
}
