/**
 * transliterate.js
 * English (roman) -> Urdu script transliteration for factory employee data.
 *
 * Dictionary lookups are exact (case-insensitive, after stray characters are
 * stripped). Anything not in a dictionary falls back to a deterministic
 * generic English->Urdu phonetic map. Empty input always returns ''.
 * There is no hardcoded default department: empty department input -> ''.
 */

import { normalizeDate } from './excel.js';

/** Department dictionary (exact entries requested). */
export const DEPT_DICT = {
  'ACCOUNTS': 'اکاؤنٹس',
  'ADMIN': 'ایڈمن',
  'ADMINISTRATION': 'ایڈمنسٹریشن',
  'BLEACHING': 'بلیچنگ',
  'BLOW ROOM': 'بلو روم',
  'BOILER': 'بوائلر',
  'BRUSHING': 'برشنگ',
  'BUNDLING': 'بنڈلنگ',
  'CAD': 'کیڈ',
  'CALENDERING': 'کیلنڈرنگ',
  'CANTEEN': 'کینٹین',
  'CARDING': 'کارڈنگ',
  'CHEMICAL STORE': 'کیمیکل اسٹور',
  'COLLAR': 'کالر',
  'COMBING': 'کومبنگ',
  'COMPLIANCE': 'کمپلائنس',
  'COMPRESSOR': 'کمپریسر',
  'CROPPING': 'کروپنگ',
  'CUFF': 'کف',
  'CUTTING': 'کٹنگ',
  'DESIGN': 'ڈیزائن',
  'DISPENSARY': 'ڈسپنسری',
  'DRAWING': 'ڈرائنگ',
  'DYEING': 'ڈائنگ',
  'ELASTIC': 'ایلاسٹک',
  'ELECTRICAL': 'الیکٹریکل',
  'EMBROIDERY': 'کڑھائی',
  'ETP': 'ای ٹی پی',
  'EXPORT': 'ایکسپورٹ',
  'FABRIC STORE': 'فیبرک اسٹور',
  'FINANCE': 'فنانس',
  'FINISHING': 'فنشنگ',
  'FINISHING (GARMENTS)': 'فنشنگ',
  'FLAT LOCK': 'فلیٹ لاک',
  'FLATLOCK': 'فلیٹ لاک',
  'FOLDING': 'فولڈنگ',
  'FUSING': 'فیوزنگ',
  'GATE': 'گیٹ',
  'GREIGE': 'گرےج',
  'GREY FABRIC': 'گرے فیبرک',
  'HR': 'ایچ آر',
  'HUMAN RESOURCE': 'ہیومن ریسورس',
  'IE': 'آئی ای',
  'IMPORT': 'امپورٹ',
  'INDUSTRIAL ENGINEERING': 'انڈسٹریل انجینئرنگ',
  'IRONING': 'استری',
  'IT': 'آئی ٹی',
  'KNITTING': 'نٹنگ',
  'LAB': 'لیب',
  'LABORATORY': 'لیبارٹری',
  'LAUNDRY': 'لانڈری',
  'MAINTENANCE': 'مینٹیننس',
  'MARKETING': 'مارکیٹنگ',
  'MECHANICAL': 'مکینیکل',
  'MERCERIZING': 'مرسرائزنگ',
  'MERCHANDISING': 'مرچنڈائزنگ',
  'MIS': 'ایم آئی ایس',
  'MOSQUE': 'مسجد',
  'OFF LINER': 'آف لائنر',
  'OFF-LINER': 'آف لائنر',
  'OFFLINE': 'آف لائن',
  'OVER LOCK': 'اوور لاک',
  'OVERLOCK': 'اوور لاک',
  'PACKING': 'پیکنگ',
  'PLANNING': 'پلاننگ',
  'POWER HOUSE': 'پاور ہاؤس',
  'POWERHOUSE': 'پاور ہاؤس',
  'PRESSING': 'پریسنگ',
  'PRINTING': 'پرنٹنگ',
  'PROCUREMENT': 'پروکیورمنٹ',
  'PRODUCTION': 'پروڈکشن',
  'PURCHASE': 'پرچیز',
  'QC': 'کیو سی',
  'QUALITY': 'کوالٹی',
  'QUALITY CONTROL': 'کوالٹی کنٹرول',
  'R&D': 'آر اینڈ ڈی',
  'RIB': 'رب',
  'RING SPINNING': 'رنگ اسپننگ',
  'ROVING': 'روونگ',
  'SALES': 'سیلز',
  'SAMPLE': 'سیمپل',
  'SAMPLE ROOM': 'سیمپل روم',
  'SANFORIZING': 'سینفورائزنگ',
  'SECURITY': 'سیکیورٹی',
  'SEWING': 'سلائی',
  'SINGEING': 'سنگنگ',
  'SIZING': 'سائزنگ',
  'SPARE PARTS': 'اسپیئر پارٹس',
  'SPINNING': 'اسپننگ',
  'STENTER': 'اسٹینٹر',
  'STITCHING': 'اسٹچنگ',
  'STORE': 'اسٹور',
  'STORES': 'اسٹورز',
  'TIME OFFICE': 'ٹائم آفس',
  'TRANSPORT': 'ٹرانسپورٹ',
  'TRIMMING': 'ٹرمنگ',
  'UTILITIES': 'یوٹیلیٹیز',
  'UTILITY': 'یوٹیلیٹی',
  'WAREHOUSE': 'ویئر ہاؤس',
  'WARPING': 'وارپنگ',
  'WASHING': 'واشنگ',
  'WEAVING': 'ویونگ',
  'WINDING': 'وائنڈنگ',
  'YARN STORE': 'یارن اسٹور',
};

/** Designation dictionary, covering the roles in the sick-leave register sample. */
export const DESIG_DICT = {
  'ACCOUNTANT': 'اکاؤنٹنٹ',
  'ADMIN OFFICER': 'ایڈمن آفیسر',
  'AM': 'اے ایم',
  'APPRENTICE': 'اپرنٹس',
  'ASSISTANT': 'اسسٹنٹ',
  'ASSISTANT MANAGER': 'اسسٹنٹ مینیجر',
  'ASST': 'اسسٹنٹ',
  'AUDITOR': 'آڈیٹر',
  'BOILER OPERATOR': 'بوائلر آپریٹر',
  'BUNDLER': 'بنڈلر',
  'BUTTON FIXING OPERATOR': 'بٹن فکسنگ آپریٹر',
  'BUTTON HOLE OPERATOR': 'بٹن ہول آپریٹر',
  'CAD OPERATOR': 'کیڈ آپریٹر',
  'CARPENTER': 'بڑھئی',
  'CASHIER': 'کیشیئر',
  'CHECKER': 'چیکر',
  'CHEMIST': 'کیمسٹ',
  'CHOWKIDAR': 'چوکیدار',
  'CLERK': 'کلرک',
  'COMPLIANCE OFFICER': 'کمپلائنس آفیسر',
  'COMPRESSOR OPERATOR': 'کمپریسر آپریٹر',
  'COMPUTER OPERATOR': 'کمپیوٹر آپریٹر',
  'CONDUCTOR': 'کنڈکٹر',
  'COOK': 'باورچی',
  'CROPPER': 'کراپر',
  'CROPPING OPERATOR': 'کروپنگ آپریٹر',
  'CUTTER': 'کٹر',
  'CUTTING MASTER': 'کٹنگ ماسٹر',
  'CUTTING OPERATOR': 'کٹنگ آپریٹر',
  'DAILY WAGER': 'دیہاڑی دار',
  'DATA ENTRY OPERATOR': 'ڈیٹا انٹری آپریٹر',
  'DEPUTY MANAGER': 'ڈپٹی مینیجر',
  'DISPENSER': 'ڈسپنسر',
  'DRIVER': 'ڈرائیور',
  'DYEING MASTER': 'ڈائنگ ماسٹر',
  'DYEING OPERATOR': 'ڈائنگ آپریٹر',
  'ELECTRICIAN': 'الیکٹریشن',
  'EMBROIDERY OPERATOR': 'کڑھائی آپریٹر',
  'EXECUTIVE': 'ایگزیکٹو',
  'FACTORY MANAGER': 'فیکٹری مینیجر',
  'FINAL CHECKER': 'فائنل چیکر',
  'FITTER': 'فٹر',
  'FLAT LOCK OPERATOR': 'فلیٹ لاک آپریٹر',
  'FLATLOCK OPERATOR': 'فلیٹ لاک آپریٹر',
  'FLOOR INCHARGE': 'فلور انچارج',
  'FOLDER': 'فولڈر',
  'FOREMAN': 'فورمین',
  'FUSING OPERATOR': 'فیوزنگ آپریٹر',
  'GARDENER': 'مالی',
  'GATE KEEPER': 'گیٹ کیپر',
  'GENERAL MANAGER': 'جنرل مینیجر',
  'GM': 'جی ایم',
  'GUARD': 'گارڈ',
  'HELPER': 'ہیلپر',
  'HR MANAGER': 'ایچ آر مینیجر',
  'HR OFFICER': 'ایچ آر آفیسر',
  'HTL MACHINE': 'ایچ ٹی ایل مشین',
  'INCHARGE': 'انچارج',
  'INTERLOCK OPERATOR': 'انٹرلاک آپریٹر',
  'IRON MAN': 'استری والا',
  'JUKI OPERATOR': 'جوکی آپریٹر',
  'KAJ OPERATOR': 'کاج آپریٹر',
  'KANSAI OPERATOR': 'کنسائی آپریٹر',
  'KANTA OPERATOR': 'کانٹا آپریٹر',
  'KARIGAR': 'کاریگر',
  'KNITTING OPERATOR': 'نٹنگ آپریٹر',
  'LAB ASSISTANT': 'لیب اسسٹنٹ',
  'LAB TECHNICIAN': 'لیب ٹیکنیشن',
  'LAUNDRY OPERATOR': 'لانڈری آپریٹر',
  'LINE CHECKER': 'لائن چیکر',
  'LINE INCHARGE': 'لائن انچارج',
  'LINE QC': 'لائن کیو سی',
  'M OPT': 'مشین آپریٹر',
  'M-OPT': 'مشین آپریٹر',
  'MACHINE OPERATOR': 'مشین آپریٹر',
  'MALI': 'مالی',
  'MANAGER': 'مینیجر',
  'MASTER CUTTER': 'ماسٹر کٹر',
  'MATE': 'میٹ',
  'MAZDOOR': 'مزدور',
  'MECHANIC': 'مکینک',
  'MERCHANDISER': 'مرچنڈائزر',
  'MISTRY': 'مستری',
  'NAIB QASID': 'نائب قاصد',
  'NURSE': 'نرس',
  'OFF LINER': 'آف لائنر',
  'OFF-LINER': 'آف لائنر',
  'OFFICER': 'آفیسر',
  'OPERATOR': 'آپریٹر',
  'OVER LOCK OPERATOR': 'اوور لاک آپریٹر',
  'OVERLOCK OPERATOR': 'اوور لاک آپریٹر',
  'PACKER': 'پیکر',
  'PAINTER': 'پینٹر',
  'PATTERN MASTER': 'پیٹرن ماسٹر',
  'PEON': 'پیون',
  'PICO OPERATOR': 'پیکو آپریٹر',
  'PLANT MANAGER': 'پلانٹ مینیجر',
  'PLUMBER': 'پلمبر',
  'PRESS MAN': 'پریس مین',
  'PRESSMAN': 'پریس مین',
  'PRINTING MASTER': 'پرنٹنگ ماسٹر',
  'PRINTING OPERATOR': 'پرنٹنگ آپریٹر',
  'PRODUCTION MANAGER': 'پروڈکشن مینیجر',
  'QUALITY CHECKER': 'کوالٹی چیکر',
  'RANGE MAN': 'رینج مین',
  'RECEPTIONIST': 'ریسپشنسٹ',
  'RIDER': 'رائیڈر',
  'SANITARY WORKER': 'سینٹری ورکر',
  'SARDAR': 'سردار',
  'SECTION INCHARGE': 'سیکشن انچارج',
  'SECURITY GUARD': 'سیکیورٹی گارڈ',
  'SENIOR EXECUTIVE': 'سینئر ایگزیکٹو',
  'SENIOR MANAGER': 'سینئر مینیجر',
  'SEWING OPERATOR': 'سلائی آپریٹر',
  'SHIFT INCHARGE': 'شفٹ انچارج',
  'SINGER NEEDLE OPERATOR': 'سنگر نیڈل آپریٹر',
  'SINGER NIDDLE OPERATOR': 'سنگر نیڈل آپریٹر',
  'SINGER OPERATOR': 'سنگر آپریٹر',
  'SPINNING OPERATOR': 'اسپننگ آپریٹر',
  'SPOT CLEANER': 'اسپاٹ کلینر',
  'STENTER OPERATOR': 'اسٹینٹر آپریٹر',
  'STITCHING OPERATOR': 'اسٹچنگ آپریٹر',
  'STORE KEEPER': 'اسٹور کیپر',
  'STOREKEEPER': 'اسٹور کیپر',
  'SUPERVISOR': 'سپروائزر',
  'SWEEPER': 'سویپر',
  'TECHNICIAN': 'ٹیکنیشن',
  'TELEPHONE OPERATOR': 'ٹیلیفون آپریٹر',
  'TIME KEEPER': 'ٹائم کیپر',
  'TRAINEE': 'ٹرینی',
  'TRIMMER': 'ٹرمر',
  'WAITER': 'ویٹر',
  'WEAVING OPERATOR': 'ویونگ آپریٹر',
  'WELDER': 'ویلڈر',
  'WELFARE OFFICER': 'ویلفیئر آفیسر',
  'WINDING OPERATOR': 'وائنڈنگ آپریٹر',
  'HTL': 'مشین آپریٹر (ایچ ٹی ایل)',
  'MOPT': 'مشین آپریٹر',
  'OPT': 'مشین آپریٹر',
  'OVERLOCK OPT': 'اوور لاک مشین آپریٹر',
  'SHAPER': 'شیپر',
};

/** Common Pakistani person-name components with correct Urdu spellings.
 * Used for 'name' and 'father' kinds before falling back to phonetic. */
export const NAME_DICT = {
  'AAMIR': 'عامر',
  'ABBAS': 'عباس',
  'ABBASI': 'عباسی',
  'ABDUL': 'عبد',
  'ABID': 'عابد',
  'ABIDA': 'عابدہ',
  'ACHAKZAI': 'اچکزئی',
  'ADNAN': 'عدنان',
  'AFRIDI': 'آفریدی',
  'AFZAL': 'افضل',
  'AGHA': 'آغا',
  'AHMAD': 'احمد',
  'AHMED': 'احمد',
  'AISHA': 'عائشہ',
  'AJMAL': 'اجمل',
  'AKHTAR': 'اختر',
  'AKMAL': 'اکمل',
  'AKRAM': 'اکرم',
  'ALI': 'علی',
  'AMINA': 'آمنہ',
  'AMIR': 'عامر',
  'AMJAD': 'امجد',
  'ANILA': 'انیلہ',
  'ANJUM': 'انجم',
  'ANSARI': 'انصاری',
  'ANWAR': 'انور',
  'ARAIN': 'آرائیں',
  'AREEBA': 'اریبہ',
  'AREEJ': 'اریج',
  'ARFAN': 'عرفان',
  'ARIF': 'عارف',
  'ARSHAD': 'ارشد',
  'ARSLAN': 'ارسلان',
  'ASHRAF': 'اشرف',
  'ASIF': 'آصف',
  'ASJAD': 'اسجد',
  'ASLAM': 'اسلم',
  'ASMA': 'اسماء',
  'AWAIS': 'اویس',
  'AWAN': 'اعوان',
  'AYAZ': 'ایاز',
  'AYESHA': 'عائشہ',
  'AYUB': 'ایوب',
  'AZIZ': 'عزیز',
  'AZIZA': 'عزیزہ',
  'BAHADUR': 'بہادر',
  'BAIG': 'بیگ',
  'BAKHSH': 'بخش',
  'BALOCH': 'بلوچ',
  'BAREERA': 'بریرہ',
  'BASHIR': 'بشیر',
  'BEGUM': 'بیگم',
  'BEHZAD': 'بہزاد',
  'BETTANI': 'بیٹنی',
  'BHAT': 'بھٹ',
  'BHATTI': 'بھٹی',
  'BIBI': 'بی بی',
  'BILAL': 'بلال',
  'BRAR': 'برار',
  'BUGTI': 'بگٹی',
  'BUKHARI': 'بخاری',
  'BUTT': 'بٹ',
  'CHAND': 'چاند',
  'CHANDIO': 'چانڈیو',
  'CHAUDHRY': 'چوہدری',
  'CHEEMA': 'چیمہ',
  'CHISHTI': 'چشتی',
  'DAD': 'داد',
  'DANISH': 'دانش',
  'DAR': 'ڈار',
  'DAWOOD': 'داؤد',
  'DHILLON': 'ڈھلوں',
  'DILAWAR': 'دلاور',
  'DILDAR': 'دلدار',
  'DIN': 'دین',
  'DUA': 'دعا',
  'EHSAN': 'احسان',
  'EMAN': 'ایمان',
  'FAHAD': 'فہد',
  'FAHEEM': 'فہیم',
  'FAISAL': 'فیصل',
  'FAIZAN': 'فیضان',
  'FARAH': 'فرح',
  'FARAZ': 'فراز',
  'FARHAD': 'فرہاد',
  'FARHAN': 'فرحان',
  'FAROOQ': 'فاروق',
  'FAROOQUI': 'فاروقی',
  'FARZANA': 'فرزانہ',
  'FATIMA': 'فاطمہ',
  'FAZIA': 'فضیہ',
  'FIAZ': 'فیاض',
  'FIZA': 'فضا',
  'FURQAN': 'فرقان',
  'GHAFFAR': 'غفار',
  'GILANI': 'گیلانی',
  'GILL': 'گل',
  'GONDAL': 'گوندل',
  'GUJJAR': 'گجر',
  'GUL': 'گل',
  'GULFAM': 'گلفام',
  'GULNAZ': 'گلناز',
  'GULSHAN': 'گلشن',
  'GULZAR': 'گلزار',
  'HABIB': 'حبیب',
  'HABIBA': 'حبیبہ',
  'HAFSA': 'حفصہ',
  'HAIDER': 'حیدر',
  'HALEEMA': 'حلیمہ',
  'HAMIDA': 'حمیدہ',
  'HAMZA': 'حمزہ',
  'HANIF': 'حنیف',
  'HANIFA': 'حنیفہ',
  'HAQ': 'حق',
  'HAROON': 'ہارون',
  'HASEEB': 'حسیب',
  'HASHIM': 'ہاشم',
  'HASHMI': 'ہاشمی',
  'HASSAN': 'حسن',
  'HINA': 'حنا',
  'HIRA': 'حرا',
  'HUSSAIN': 'حسین',
  'IBRAHIM': 'ابراہیم',
  'IDRIS': 'ادریس',
  'IKRAM': 'اکرام',
  'IMRAN': 'عمران',
  'IMTIAZ': 'امتیاز',
  'INAM': 'انعام',
  'IQRA': 'اقرا',
  'IRFAN': 'عرفان',
  'IRSHAD': 'ارشاد',
  'ISA': 'عیسیٰ',
  'ISHAQ': 'اسحاق',
  'ISMAIL': 'اسماعیل',
  'JABBAR': 'جبار',
  'JAFRI': 'جعفری',
  'JAMALI': 'جمالی',
  'JAN': 'جان',
  'JATOI': 'جتوئی',
  'JAVED': 'جاوید',
  'JUNAID': 'جنید',
  'JUTT': 'جٹ',
  'KAKAR': 'کاکڑ',
  'KALEEM': 'کلیم',
  'KAMRAN': 'کامران',
  'KAREEM': 'کریم',
  'KAZMI': 'کاظمی',
  'KHADIJA': 'خدیجہ',
  'KHALID': 'خالد',
  'KHAN': 'خان',
  'KHATOON': 'خاتون',
  'KHATTAK': 'خٹک',
  'KHOKHAR': 'کھوکھر',
  'KHWAJA': 'خواجہ',
  'KIRAN': 'کرن',
  'KOUSAR': 'کوثر',
  'LAL': 'لال',
  'LASHARI': 'لاشاری',
  'LATEEF': 'لطیف',
  'LATIFA': 'لطیفہ',
  'LONE': 'لون',
  'LUQMAN': 'لقمان',
  'MAHAM': 'ماہم',
  'MAHAR': 'مہر',
  'MAHIRA': 'ماہرہ',
  'MAHMOOD': 'محمود',
  'MAHNOOR': 'ماہ نور',
  'MALIK': 'ملک',
  'MANAHIL': 'مناہل',
  'MANSHA': 'منشا',
  'MANZOOR': 'منظور',
  'MAQSOOD': 'مقصود',
  'MARWAT': 'مروت',
  'MARYAM': 'مریم',
  'MASOOD': 'مسعود',
  'MEHMOOD': 'محمود',
  'MEHNAZ': 'مہناز',
  'MEHSUD': 'محسود',
  'MEMON': 'میمن',
  'MENGAL': 'مینگل',
  'MINAHIL': 'مناہل',
  'MIR': 'میر',
  'MIRZA': 'مرزا',
  'MOOSA': 'موسیٰ',
  'MUGHAL': 'مغل',
  'MUHAMMAD': 'محمد',
  'MUKHTAR': 'مختار',
  'MUMTAZ': 'ممتاز',
  'MUNIR': 'منیر',
  'MURAD': 'مراد',
  'MUSKAN': 'مسکان',
  'NABI': 'نبی',
  'NADEEM': 'ندیم',
  'NADIA': 'نادیہ',
  'NAEEM': 'نعیم',
  'NAFEESA': 'نفیسہ',
  'NAQVI': 'نقوی',
  'NASEEM': 'نسیم',
  'NASIR': 'ناصر',
  'NASREEN': 'نسرین',
  'NAZIA': 'نازیہ',
  'NAZIR': 'نذیر',
  'NIAZ': 'نیاز',
  'NIZAMI': 'نظامی',
  'NOMAN': 'نعمان',
  'NOOR': 'نور',
  'OMAR': 'عمر',
  'PARVEEN': 'پروین',
  'PARVEZ': 'پرویز',
  'PIR': 'پیر',
  'QADIR': 'قادر',
  'QASIM': 'قاسم',
  'QURESHI': 'قریشی',
  'RABIA': 'رابعہ',
  'RAHEEM': 'رحیم',
  'RAJA': 'راجہ',
  'RAJPUT': 'راجپوت',
  'RANJHA': 'رانجھا',
  'RASHID': 'راشد',
  'RASHIDA': 'راشدہ',
  'RASOOL': 'رسول',
  'REHAN': 'ریحان',
  'REHMAN': 'رحمان',
  'RIAZ': 'ریاض',
  'RIMSHA': 'رمشا',
  'RIND': 'رند',
  'RIZVI': 'رضوی',
  'RIZWAN': 'رضوان',
  'RUQAYA': 'رقیہ',
  'RUQSANA': 'رقصانہ',
  'SAAD': 'سعد',
  'SABAH': 'صباح',
  'SABRI': 'صابری',
  'SADIA': 'سعدیہ',
  'SAJID': 'ساجد',
  'SAJIDA': 'ساجدہ',
  'SAJJAD': 'سجاد',
  'SALEEM': 'سلیم',
  'SALMA': 'سلمیٰ',
  'SALMAN': 'سلمان',
  'SAMINA': 'ثمینہ',
  'SANA': 'ثنا',
  'SANDHU': 'سندھو',
  'SAQLAIN': 'ثقلین',
  'SARFRAZ': 'سرفراز',
  'SARKAR': 'سرکار',
  'SARWANI': 'سروانی',
  'SARWAR': 'سرور',
  'SATTAR': 'ستار',
  'SAWERA': 'سویرا',
  'SHABANA': 'شبانہ',
  'SHABBIR': 'شبیر',
  'SHAH': 'شاہ',
  'SHAHBAZ': 'شہباز',
  'SHAHID': 'شاہد',
  'SHAHNAZ': 'شہناز',
  'SHAHZAD': 'شہزاد',
  'SHAKIR': 'شاکر',
  'SHAMIM': 'شمیم',
  'SHARIF': 'شریف',
  'SHAZIA': 'شازیہ',
  'SHEIKH': 'شیخ',
  'SHER': 'شیر',
  'SIAL': 'سیال',
  'SIDDIQUE': 'صدیق',
  'SIDDIQUI': 'صدیقی',
  'SIDHU': 'سدھو',
  'SOHAIL': 'سہیل',
  'SULEMAN': 'سلیمان',
  'SULTAN': 'سلطان',
  'SUMAIRA': 'سمیرا',
  'SYED': 'سید',
  'TAHIR': 'طاہر',
  'TALHA': 'طلحہ',
  'TANOLI': 'تنولی',
  'TANVEER': 'تنویر',
  'TARIQ': 'طارق',
  'TASLEEM': 'تسلیم',
  'TAYYAB': 'طیب',
  'THAHIM': 'تھہیم',
  'TOUSEEF': 'توسیف',
  'UMAIR': 'عمیر',
  'UMAR': 'عمر',
  'UNAIB': 'عنیب',
  'USMAN': 'عثمان',
  'UZMA': 'عظمیٰ',
  'VIRK': 'ورک',
  'WAHEEDA': 'وحیدہ',
  'WANI': 'وانی',
  'WAQAR': 'وقار',
  'WAQAS': 'وقاص',
  'WASEEM': 'وسیم',
  'WAZIR': 'وزیر',
  'YAQOOB': 'یعقوب',
  'YASIR': 'یاسر',
  'YOUSAF': 'یوسف',
  'YOUSAFZAI': 'یوسفزئی',
  'YOUSUF': 'یوسف',
  'YUNUS': 'یونس',
  'ZAHID': 'زاہد',
  'ZAIDI': 'زیدی',
  'ZAINAB': 'زینب',
  'ZAKIR': 'ذاکر',
  'ZAKRIA': 'زکریا',
  'ZARA': 'زارا',
  'ZEESHAN': 'ذیشان',
  'ZUBAIR': 'زبیر',
  'ZUNAIRA': 'زنیرہ',
};


/** Common reason phrases. */
export const REASON_DICT = {
  'DUE TO SICK': 'بیماری کی وجہ سے',
  'DUE TO ILLNESS': 'بیماری کی وجہ سے',
  'SICK LEAVE': 'بیماری کی وجہ سے',
  SICK: 'بیماری کی وجہ سے',
  'DUE TO FEVER': 'بخار کی وجہ سے',
  FEVER: 'بخار کی وجہ سے',
  CASUAL: 'اتفاقی کام کی وجہ سے',
  ANNUAL: 'سالانہ چھٹی',
};

const cleanKey = (text) =>
  String(text)
    .replace(/[\\/:;]+/g, ' ') // strip stray characters first
    .replace(/\s+/g, ' ')
    .trim()
    .toUpperCase();

/* Generic English -> Urdu phonetic map (deterministic best-effort fallback). */
const DIGRAPHS = [
  ['kh', 'کھ'],
  ['gh', 'غ'],
  ['ch', 'چ'],
  ['sh', 'ش'],
  ['th', 'تھ'],
  ['ph', 'ف'],
  ['bh', 'بھ'],
  ['dh', 'دھ'],
  ['zh', 'ژ'],
  ['ng', 'نگ'],
  ['oo', 'و'],
  ['ee', 'ی'],
  ['ou', 'اؤ'],
  ['ai', 'ای'],
  ['au', 'اؤ'],
];

const LETTERS = {
  a: 'ا', b: 'ب', c: 'ک', d: 'د', e: 'ی', f: 'ف', g: 'گ', h: 'ہ',
  i: 'ی', j: 'ج', k: 'ک', l: 'ل', m: 'م', n: 'ن', o: 'و', p: 'پ',
  q: 'ق', r: 'ر', s: 'س', t: 'ت', u: 'و', v: 'و', w: 'و', x: 'کس',
  y: 'ی', z: 'ز',
};

function phonetic(text) {
  const s = String(text).toLowerCase();
  let out = '';
  let i = 0;
  while (i < s.length) {
    let matched = false;
    if (i + 1 < s.length) {
      const pair = s.slice(i, i + 2);
      const dig = DIGRAPHS.find(([d]) => d === pair);
      if (dig) {
        out += dig[1];
        i += 2;
        matched = true;
      }
    }
    if (!matched) {
      const ch = s[i];
      out += LETTERS[ch] !== undefined ? LETTERS[ch] : ch; // digits/spaces pass through
      i += 1;
    }
  }
  return out;
}

/**
 * Transliterate a roman-English string into Urdu script.
 * kind: 'name' | 'father' | 'designation' | 'department' | 'reason'.
 * Empty input -> ''. Department input that is empty -> '' (no defaults).
 */
export function transliterate(text, kind) {
  if (text === null || text === undefined) return '';
  const cleaned = String(text)
    .replace(/[\\/:;]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  if (!cleaned) return '';

  const key = cleanKey(cleaned);
  const dict =
    kind === 'department' ? DEPT_DICT
    : kind === 'designation' ? DESIG_DICT
    : kind === 'reason' ? REASON_DICT
    : kind === 'name' || kind === 'father' ? NAME_DICT
    : null;

  if (dict && dict[key]) return dict[key];

  // Department values often carry a unit number, e.g. 'STITCHING 04'.
  if (kind === 'department') {
    const m = key.match(/^(.+?)[\s\-]*(\d+)$/);
    if (m && DEPT_DICT[m[1].trim()]) {
      return `${DEPT_DICT[m[1].trim()]} ${m[2]}`;
    }
  }

  // For multi-word names, translate word-by-word when the full phrase
  // is not in the dictionary (e.g. "MUHAMMAD ASLAM" -> "محمد اسلم").
  if ((kind === 'name' || kind === 'father') && dict) {
    const words = key.split(' ').filter(Boolean);
    if (words.length > 1) {
      const parts = words.map((w) => dict[w]);
      if (parts.every(Boolean)) return parts.join(' ');
    }
  }

  return phonetic(cleaned);
}

/**
 * Transliterate one raw sheet row into form-ready data.
 * row: raw object keyed by header; mapping: { ecode, name, father,
 *   designation, department, date, reason } as returned by detectColumns
 *   (values are header strings or null).
 * opts: optional { month, year } for bare day-number dates.
 */
export function transliterateRow(row, mapping, opts = {}) {
  const get = (field) =>
    mapping && mapping[field] != null ? row[mapping[field]] : '';
  return {
    ecode: String(get('ecode') ?? '').trim(),
    name: transliterate(get('name'), 'name'),
    father: transliterate(get('father'), 'father'),
    designation: transliterate(get('designation'), 'designation'),
    department: transliterate(get('department'), 'department'),
    date: normalizeDate(get('date'), opts.month, opts.year) || '',
    reason: transliterate(get('reason'), 'reason'),
  };
}
